# Site
name: "Mediumish"
title: "Mediumish"
description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mediumish-theme-jekyll
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
    puneeth:
      short_name:     puneeth
      name:           Neerukonda Puneeth
      site:           https://puneethkanna.github.io
      avatar:         /assets/images/puneeth.jpg
      bio:            "Student Developer, Tech Enthusiastic, love to browse the Internet!"
      email:          neerukondapuneeth@gmail.com
      twitter:        https://twitter.com/puneeth_kanna
    mohit:
      short_name:     mohit
      name:           Indukuri Mohit
      site:           https://puneethkanna.github.io
      avatar:         /assets/images/mohit.jpeg
      bio:            "Tech Enthusiastic, love to browse the Internet!"
      email:          mohitindukuri100@gmail.com
      twitter:        https://twitter.com/indukuri_mohit
    nikhil:
      short_name:     nikhil
      name:           Nikhil Reddy Pyreddy
      site:           https://nikhilpyreddy.me/
      avatar:         /assets/images/nikhil.jpg
      bio:            "Student Developer, Tech Enthusiastic, love to browse the Internet!"
      email:          nikhilpyreddy@gmail.com
      twitter:        https://twitter.com/NPyreddy
    satya:
      short_name:     satya
      name:           Sri Satya Lokesh Karri
      site:           https://srisatyalokesh.github.io
      avatar:         /assets/images/satya.jpg
      bio:            "Software Engineer at Dhan AI. Python Developer, Tech Enthusiastic, Photographer"
      email:          satya@devskrate.com
      twitter:        https://twitter.com/CodeWithSatya
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
